train:
  - order: 'chorno' # chorno means training mini-batches are formed in chronological order
    epoch: 200
    save_every: 50
    batch_size: 600
    lr: 0.0001
    dropout: 0.1
eval:
  - batch_size: 100
    val_epoch: 0  # the training epoch that start evaluation on the validation set
scope:
  - layer: 2
    neighbor:
      - 20
      - 20
    strategy: 'recent'
gnn:
  - arch: 'mixer'
    layer: 2
    att_head: 2
    time_enc: 'learnable'
    dim_time: 100
    dim_out: 100
    memory_type: 'gru'
    dim_memory: 100
    msg_reducer: 'last'
    memory_update_use_embed: False
