train:
  - order: 'chorno' # chorno means training mini-batches are formed in chronological order
    epoch: 400
    batch_size: 600
    lr: 0.0001
    dropout: 0.1
eval:
  - batch_size: 100
    val_epoch: 100  # the training epoch that start evaluation on the validation set
scope:
  - layer: 1
    neighbor:
      - 20
      # - 20
    strategy: 'uniform'
sample:
  # - type: 'adapt'
  - type: 'none'
    neighbor: 10
    freq_encode: 'sin'
    keep_dummy_freq: true
    identity_encode: false
    dim_feat: 100
    dim_encode: 100
    feat_norm: true
    neigh_norm: false
    mixer: false
    decoder: 'gat_v1'
    init_gain: 0.01
    unif_bias: True
    lr: 0.0001
    weight_decay: 0
    att_clamp: 5
gnn:
  - arch: 'transformer'
    layer: 2
    att_head: 2
    time_enc: 'learnable'
    dim_time: 100
    dim_out: 100
    memory_type: 'gru'
    dim_memory: 150
    msg_reducer: 'mean'
